website/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


#یو آر ال های مربوط به اپ accounts در اینحا تعریف می شوند.
app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name="login"),
    path('profile/', views.profile, name='profile'), 
    path('logout/', views.signout, name='logout'), 
    path('change_password/', views.change_password, name='change_password'),
] 


if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/qa/urls.py
from django.urls import path
from .views import external_qa_page, ask_question, edit_question, show_answers, save_answer, cpecific_answer, delete, delete_all
from django.conf.urls.static import static
from django.conf import settings

#این اپ دارای صفحه های  :
#پرسش سوال
#ویرایش سوال
#دادن جواب
#حذف سوال
#حذف تمامی سوالات
#صفحه ای که 10 سوال و جوابهای آنها را به صورت تصادفی نمایش می دهد.
app_name = 'qa'
urlpatterns = [
    path('search/', external_qa_page, name='external_qa_page'),
    path('ask_question/', ask_question, name='ask_questions'),
    path('edit_question/<int:id>', edit_question, name='edit_question'),
    path('show_answers/<int:id>', show_answers, name='show_answers'),
    path('answer/<int:id>', save_answer, name='save_answer'),
    path('specific_answers/<int:id>', cpecific_answer, name='specific_answers'),
    path('delete/<int:id>', delete, name='delete_question'),
    path('delete-all/', delete_all, name='delete_all_questions')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('golgavzabon/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('plant_leaf_deseases_detector/', include('PLDdetector.urls', namespace='PLDdetector')),
    path('my_plants/', include('my_plants.urls', namespace='my_plants')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('house_plant_species_detector/', include('house_plant_species_detector.urls', namespace='house_plant_species_detector')),
    path('approachs/', include('approachs.urls', namespace='approachs'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/qa/models.py
from django.db import models
from accounts.models import User

#مدلی است که برای ثبت سوال ساخته شده است.
class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions')#هر سوال یک فیلد به نام user دارد که بیان کننده کاربر ثبت کننده آن است. به گونه ای که با مدل User در ارتباط است و هر کاربر می تواند چندسوال داشته باشد
    #هر سوال می تواند درباره یکی از موضوعات زیر باشد
    topics = (
        ('a', 'مشکل یا بیماری گیاهان'),
        ('b', 'نحوه نگهداری'),
        ('c', 'مواد مغذی گیاهان'),
        ('d', 'ظاهر گیاهان'),
        ('e', 'اطلاعات عمومی درباره گیاهان'),
        ('f', 'روش های تکثیر گیاهان'),
        ('g', 'زادگاه گیاهان'),
        ('h', 'خاک گیاه'),
        ('i', 'آب گیاه'),
        ('j', 'نور گیاه'),
        ('k', 'دما و رطوبت گیاه'),
        ('l', 'هرس کردن گیاه'),
        ('m', 'محصولات گیاه'),
        ('n', 'نام کاشف'),
        ('o', 'محل اکتشاف'),
        ('p', 'نام علمی گیاهان'),
        ('q', 'نام فارسی گیاهان'),

    )

    topic = models.CharField(max_length=100, choices=topics, blank=True, null=True)

    title = models.CharField(max_length=100)
    detail = models.TextField()
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

#این مدل بریا ذخیره جواب ساخته شده است
class Answer(models.Model):
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)#هر جواب می تواند یک سوال داشته باشد.
    user = models.ForeignKey(User, related_name='answers', on_delete=models.CASCADE)
    detail = models.TextField()
    creation_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Answer by {self.user.username} to: {self.question.title}"

website/qa/forms.py
from django import forms
from .models import Question, Answer

#پرسش سوال
class AskingQuestion(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'detail', 'topic']

        widgets = {
            'title': forms.TextInput(attrs={
                'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
            }),
            'detail': forms.Textarea(attrs={
                'style': 'width: 100%; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 200px; resize: vertical;',
                'maxlength' : "1000",
            }),
            'topic': forms.Select(attrs={
                'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
            })
        }

#تغییر سوال
class QuestionEdit(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'detail', 'topic']

        widgets = {
            'title': forms.TextInput(attrs={
                'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
            }),
            'detail': forms.Textarea(attrs={
                'style': 'width: 100%; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 200px; resize: vertical;',
            }),
            'topic': forms.Select(attrs={
                'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
            })
        }

#ثبت پاسخ
class SaveAnswer(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['detail']

        widgets = {
                    'detail': forms.TextInput(attrs={
                        'style': 'width: 100%; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 200px; resize: vertical;',
                    })}

#جستوجو در سوالات
class SearchQuestions(forms.Form):
    query = forms.CharField(max_length=100, widget=forms.TextInput({'placeholder' : "جستوجو",
                                                                    'style': 'width: 100%; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',

                                                                    }))

website/qa/views.py
from django.shortcuts import render, redirect
from .forms import AskingQuestion, QuestionEdit, SaveAnswer, SearchQuestions
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Question, Answer
from django.db.models import Prefetch
import random
from django.db.models import Q


#این صفحه 10 سوال را به صورت تصادفی انتخاب کرده و نمایش می دهد. امکاکن ثبت سوال جدید یا پاسخ به سوالات دیگران را فراهم می کند و قابلیت جستوجو در تمامی سوالات ثبت شده را دارا است.
def external_qa_page(request):

    query = request.GET.get('query')

    search_form = SearchQuestions()

    if query:
        question_ids = list(Question.objects.filter(
            Q(title__icontains=query) |
            Q(detail__icontains=query) |
            Q(topic__icontains=query)
        ).values_list('id', flat=True))
    else:
        question_ids = list(Question.objects.values_list('id', flat=True))

    random.shuffle(question_ids)

    question_ids = question_ids[:10]

    # Get questions and prefetch related answers
    questions_with_answers = Question.objects.filter(id__in=question_ids).prefetch_related(
        Prefetch('answers', queryset=Answer.objects.all()))

    return render(request, 'qa/external_question_page.html', {'questions_with_answers': questions_with_answers, 'search_form' : search_form})

#بقیه موارد مشابه ویو های پیشین هستند
def search_questions(request):
    query = request.GET.get('q')
    if query:
        results = Question.objects.filter(
            Q(question_text__icontains=query) |
            Q(topic__icontains=query) |
            Q(custom_topic__icontains=query)
        )
    else:
        results = Question.objects.all()
    return render(request, 'qa/external_question_page.html', {'results': results})


def ask_question(request):
    if request.method == 'POST':
        form = AskingQuestion(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()

            messages.success(request,'شوال شما با موفقیت ثبت شد.')
            return redirect('accounts:profile')
    else:
        form = AskingQuestion()
    return render(request, 'qa/ask_question.html', {'form': form})


def edit_question(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == 'POST':
        form = QuestionEdit(request.POST, instance=question)

        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()

            return redirect('accounts:profile')

    else:
        form = QuestionEdit(instance=question)
    context = {'form': form, 'question_title' : question.title}

    return render(request, 'qa/edit_question.html', context)


def show_answers(request, id):
    question = Question.objects.get(id=id)
    answers = question.answer.all()

    return render(request, 'qa/answers.html', {'answers' : answers})


def save_answer(request, id):
    question = Question.objects.get(id=id)

    if request.method == 'POST':
        form = SaveAnswer(request.POST)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.user = request.user

            answer.save()

            messages.success(request, 'پاسخ شما با موفقیت ثبت شد.')
            return redirect('home:home')

    else:
        form = SaveAnswer()

        context = {'form' : form,
                   'question' : question
                   }
    return render(request, 'qa/save_answer.html',context)


def cpecific_answer(request, id):
    question = Question.objects.get(id=id)
    answers = question.answers.all()

    return render(request, 'qa/specific_answers.html', {'answers' : answers, 'question' : question})


def delete(request, id):
    question = Question.objects.get(id=id)

    question.delete()
    messages.success(request, 'سوال شما با موفقیت حذف شد')
    return redirect('accounts:profile')


def delete_all(request):
    questions = request.user.questions.all()

    questions.delete()
    messages.success(request, 'تمامی سوالات حذف شدند')
    return redirect('accounts:profile')

website/qa/templates/qa/answers.html
{% extends 'base.html' %}
{% block title %}
    answers
{% endblock %}

{% block body%}
    <div class="page-container">
        {% for answer in answers %}
            <p>{{ answer.detail }}</p>
        {% endfor %}
    </div>

    <style>
    .page-container{
        margin: 0 20px;
    }
    </style>
{% endblock %}

website/qa/templates/qa/ask_question.html
{% extends 'base.html' %}

{% block title %}
    my_questions
{% endblock %}

{% block body %}
    <style>

        .heading {
            color: white;
        }

        .form-title, .form-topic, .form-detail {
            color: white;
        }

        .submit-button {
            background-color: #13C055FC;
            color: white;
            border: 1px #13C055FC solid;
            border-radius: 10px;
            width: 300px;
            height: 30px;
        }

        .container {
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
        }

        @media screen and (max-width: 768px) {
            .container {
                width: calc(100% - 40px); /* Ensures 20px space from edges */
                margin: 20px;
                align-items: stretch;
            }

            .submit-button {
                width: 100%;
                max-width: 300px;
            }
        }
    </style>

    <div class="background">
        <ul><h1 class="heading">پرسش سوال</h1></ul><br>
    </div><br>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p class="form-title">سرتیتر</p>
            {{ form.title }}<br><br>
            <p class="form-topic">سوال شما در چه موردی است؟</p>
            {{ form.topic }}<br><br>
            <p class="form-detail">جزئیات سوال</p>
            {{ form.detail }}<br><br>
            <button type="submit" class="submit-button">ثیت سوال</button>
        </form>
    </div><br>
{% endblock %}

website/qa/templates/qa/edit_question.html
{% extends 'base.html' %}

{% block title %}
    my_questions
{% endblock %}

{% block body %}
    <style>
        .background {
            background: linear-gradient(to right, rgb(43,48,52), rgba(89,91,93,0.79));
        }

        .heading {
            color: white;
        }


        .form-title, .form-topic, .form-detail {
            color: white;
        }

        .submit-button {
            background-color: #13C055FC;
            color: white;
            border: 1px lightgray solid;
            border-radius: 10px;
            width: 300px;
            height: 30px;
        }
    </style>

    <div class="background">
        <ul><h1 class="heading">وارایش سوال {{ question_title }}</h1></ul><br>
    </div><br>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p class="form-title">سرتیتر</p>
            {{ form.title }}<br><br>
            <p class="form-topic">سوال شما در چه موردی است؟</p>
            {{ form.topic }}
            <p class="form-detail">جزئیات سوال</p>
            {{ form.detail }}<br>
            <button type="submit" class="submit-button">ثیت ویریش</button>
        </form>
    </div><br>
{% endblock %}

website/qa/templates/qa/external_question_page.html
{% extends 'base.html' %}
{% block title %}
    Random Questions and Answers
{% endblock %}

{% block body %}
    <style>
    .question-header, answer-header {
        width: 100%;
        margin: 0 20px;
    }

    svg {
        fill: white;
        width: 40px;
    }

    .container {
        background-color: rgb(60, 60, 61);
        padding: 10px;
        border-radius: 20px;
        border: 1px #696969 solid;
    }

    .page-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    form {
        margin: 0 100px;
    }


    strong {
        color: white;
    }

    .question-detail {
        color: lightgray;
    }
    .answer-detail{
        color: white;
    }

    .answer-button,.ask-question-button {
        display: flex; /* Ensures width and height are respected */
        height: 40px;
        width: 300px;
        color: white;
        background-color: #3cbd41;
        border-radius: 10px;
        transition: 0.2s;
        justify-content: center;
        align-items: center;
        transition: 0.2s;
    }

    .answer-button:hover,.ask-question-button:hover {
        background-color: #85d286;
    }

    .answer-container {
        background-color: #3f4250;
        border: 1px #676767 solid;
        border-radius: 20px;
        padding: 10px;
    }
    </style>

    <div class="page-container">
<div>
    <h1 class="main-heading" style="color: white">صفحه پرسش و پاسخ</h1>
    <div style="display: flex; justify-content: center">
        <a href="{% url 'qa:ask_questions' %}" class="ask-question-button">شما سوال بپرسید</a><br><br>
    </div><br>
</div>

<ul>
    <form method="get" action="{% url 'qa:external_qa_page' %}">
        {% csrf_token %}
        {{ search_form.query }}
    </form><br>

    {% for question in questions_with_answers %}
    <div>
        <ul>
            <div class="question-header">
                <svg xmlns="http://www.w3.org/2000/svg" class="question-icon" viewBox="0 0 16 16">
                    <path d="M8.05 9.6c.336 0 .504-.24.554-.627.04-.534.198-.815.847-1.26.673-.475 1.049-1.09 1.049-1.986 0-1.325-.92-2.227-2.262-2.227-1.02 0-1.792.492-2.1 1.29A1.7 1.7 0 0 0 6 5.48c0 .393.203.64.545.64.272 0 .455-.147.564-.51.158-.592.525-.915 1.074-.915.61 0 1.03.446 1.03 1.084 0 .563-.208.885-.822 1.325-.619.433-.926.914-.926 1.64v.111c0 .428.208.745.585.745"/>
                    <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911z"/>
                    <path d="M7.001 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0"/>
                </svg>
                <strong>{{ question.user }} : {{ question.title }}</strong>
            </div>
        </ul>

        <div class="container">
            <p class="question-detail">{{ question.detail }}</p>
        </div><br>

        {% for answer in question.answers.all %}
        <ul>
            <div class="answer-header">
                <svg xmlns="http://www.w3.org/2000/svg" class="answer-icon" viewBox="0 0 16 16">
                    <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a2 2 0 0 0-.453-.618A5.98 5.98 0 0 1 2 6m6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1"/>
                </svg>
                <strong>{{ answer.user.username }}</strong>
            </div>
        </ul>
                <div class="answer-container">
                    <p class="answer-detail">{{ answer.detail }}</p>
                </div>
        {% empty %}
        <ul>
            <p class="no-answers">هنوز جوابی وجود ندارد</p>
        </ul>
        {% endfor %}<br>
        <div style="display: flex; justify-content: center">
            <a href="{% url 'qa:save_answer' question.id %}" class="answer-button" style="height: 30px">پاسخ دهید</a><br><br><hr style="color: white">
        </div>
        <hr style="color: white">
    {% endfor %}
</div><br><br>
</ul><br>

    </div>
{% endblock %}

website/qa/templates/qa/save_answer.html
{% extends 'base.html' %}
{% block title %}
    answers
{% endblock %}

{% block body %}
    <style>
    .container {
        border-radius: 20px;
        height: 400px;
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 10px;
    }

    form {
        width: 100%;
    }
    .detail-container {
        background-color: #262a33;
        border-radius: 10px;
        border: 1px gray solid;
        margin: 20px auto;
    }

    .submit-button {
        background-color: #25b238;
        height: 30px;
        width: 300px;
        border: 1px #25b238 solid;
        border-radius: 10px;
        color: white;
        margin: auto;
        display: block;
    }

    @media screen and (max-width: 768px) {
        .container, .detail-container {
            width: 100%;
        }

        .submit-button {
            width: 100%;
        }
    }
    </style>
    <h1 style="color: white; margin-right: 20px" >
    ثبت پاسخ
    </h1>
    <ul>
        <div class="question-container" style="text-align: center;">
        <svg xmlns="http://www.w3.org/2000/svg" class="question-icon" viewBox="0 0 16 16" style="fill: white; width: 50px">
            <path d="M8.05 9.6c.336 0 .504-.24.554-.627.04-.534.198-.815.847-1.26.673-.475 1.049-1.09 1.049-1.986 0-1.325-.92-2.227-2.262-2.227-1.02 0-1.792.492-2.1 1.29A1.7 1.7 0 0 0 6 5.48c0 .393.203.64.545.64.272 0 .455-.147.564-.51.158-.592.525-.915 1.074-.915.61 0 1.03.446 1.03 1.084 0 .563-.208.885-.822 1.325-.619.433-.926.914-.926 1.64v.111c0 .428.208.745.585.745"/>
            <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911z"/>
            <path d="M7.001 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0"/>
        </svg>
        <strong style="color: white">{{ question.user.username }}:{{ question.title }}</strong>

        <div class="detail-container">
            <div >
                <p style="color: lightgray">{{ question.detail }}</p>
            </div>

        </div>

    </div>
    </ul>

    <div class="container">
        <form method="post">
        {% csrf_token %}
            <p style="color: lightgray">پاسخ:</p>
        {{ form.detail }}
        <br><br>
            {% if user.is_authenticated %}
                <button type="submit" class="submit-button">ثبت پاسخ</button>
            {% else %}
                <a href="{% url 'accounts:login' %}" style="background-color: #25b238; height: 30px; width: 300px; border: 1px #25b238 solid; border-radius: 10px; color: white; display: flex; justify-content: center; align-items: center;">ثبت پاسخ</a>
            {% endif %}
        </form>
    </div>

{% endblock %}

website/qa/templates/qa/specific_answers.html
{% extends 'base.html' %}
{% block title %}
    answers
{% endblock %}

{% block body %}
    <style>
        .icon {
            width: 40px;
            height: 40px;
            fill: white;
        }

        .question-user {
            color: white;
        }

        .container {
            border-radius: 10px;
            border: 1px gray solid;
            background-color: #262a33;
            display: flex;
            justify-content: start;
            align-items: center;
        }

        .answer-user {
            color: white;
        }

        .answer-detail {
            color: white;
        }

        .no-answer {
            color: white;
        }

        .ask-question-btn {
            display: flex;
            border-radius: 10px;
            background-color: #13C055FC;
            height: 30px;
            width: 300px;
            align-items: center;
            justify-content: center;
            color: white;
            margin: auto;
            border: 1px lightgray solid;
            transition: 0.3s;
        }
        .ask-question-btn:hover {
            background-color: #7dd27f;
        }
    </style>

    <ul>
    <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="icon bi bi-patch-question" viewBox="0 0 16 16">
            <path d="M8.05 9.6c.336 0 .504-.24.554-.627.04-.534.198-.815.847-1.26.673-.475 1.049-1.09 1.049-1.986 0-1.325-.92-2.227-2.262-2.227-1.02 0-1.792.492-2.1 1.29A1.7 1.7 0 0 0 6 5.48c0 .393.203.64.545.64.272 0 .455-.147.564-.51.158-.592.525-.915 1.074-.915.61 0 1.03.446 1.03 1.084 0 .563-.208.885-.822 1.325-.619.433-.926.914-.926 1.64v.111c0 .428.208.745.585.745" />
            <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911z" />
            <path d="M7.001 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0" />
        </svg>
        <strong class="question-user">{{ question.user }} : {{ question.title }}</strong>
    </div>
    </ul>

    <div class="container">
        <p class="question-user">{{ question.detail }}</p>
    </div>

    {% for answer in answers %}
        <ul>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon bi bi-lightbulb" viewBox="0 0 16 16">
                    <path d="M2 6a6 6 0 1 1 10.174 4.31c-.203.196-.359.4-.453.619l-.762 1.769A.5.5 0 0 1 10.5 13a.5.5 0 0 1 0 1 .5.5 0 0 1 0 1l-.224.447a1 1 0 0 1-.894.553H6.618a1 1 0 0 1-.894-.553L5.5 15a.5.5 0 0 1 0-1 .5.5 0 0 1 0-1 .5.5 0 0 1-.46-.302l-.761-1.77a2 2 0 0 0-.453-.618A5.98 5.98 0 0 1 2 6m6-5a5 5 0 0 0-3.479 8.592c.263.254.514.564.676.941L5.83 12h4.342l.632-1.467c.162-.377.413-.687.676-.941A5 5 0 0 0 8 1" />
                </svg>
                <strong class="answer-user">{{ answer.user.username }}</strong>
            </div>
        </ul>
        <div class="container">
            <p class="answer-detail">{{ answer.detail }}</p>
        </div>
        <hr class="answer-detail" />
    {% empty %}
        <ul>
            <p class="no-answer">هنوز جوابی وجود ندارد</p>
        </ul>
    {% endfor %}
    <br><br>

    <a href="{% url 'qa:ask_questions' %}" class="ask-question-btn">سوال جدید بپرسید</a>
    <br>
{% endblock %}