website/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


#یو آر ال های مربوط به اپ accounts در اینحا تعریف می شوند.
app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name="login"),
    path('profile/', views.profile, name='profile'), 
    path('logout/', views.signout, name='logout'), 
    path('change_password/', views.change_password, name='change_password'),
] 


if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/approachs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'approachs'
urlpatterns = [
    path('send_approach/', views.send_approach, name='send_approach'),
    path('approach_answer/<int:id>', views.approach_answer, name='approach_answer'),
    path('delete/<int:id>', views.delete, name='delete_approach'),
    path('delete_all/', views.delete_all, name='delete_all_approachs'),
    path('edit_approach/<int:id>', views.edit_approach, name='edit_approach')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/urls.py
from django.urls import path
from .views import home
from django.conf import settings
from django.conf.urls.static import static


app_name = "home"
urlpatterns = [
    path('', home, name="home")
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/my_plants/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#برای نشان دادن توضیحات و پروفایل هر گیاه، حذف و اضافه کردن گیاهان به پروفال کاربر باید id گیاه از طرف لینک ارجاع دهنده دریافت شود.
app_name = 'my_plants'
urlpatterns = [
    path('house plants names/', views.house_plants_names, name='house_plants_names'),
    path('house plants names/<int:id>/', views.plant_detail, name='plant_detail'),
    path('plant_adder/<int:plant_id>/', views.user_plant_adder, name='user_plant_adder'),
    path('plant_remover/<int:plant_id>/', views.user_plant_remover, name='user_plant_remover'),
    path('plant_remover_all/', views.user_plant_remover_all, name='user_plant_remover_all'),
]
if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/qa/urls.py
from django.urls import path
from .views import external_qa_page, ask_question, edit_question, show_answers, save_answer, cpecific_answer, delete, delete_all
from django.conf.urls.static import static
from django.conf import settings

#این اپ دارای صفحه های  :
#پرسش سوال
#ویرایش سوال
#دادن جواب
#حذف سوال
#حذف تمامی سوالات
#صفحه ای که 10 سوال و جوابهای آنها را به صورت تصادفی نمایش می دهد.
app_name = 'qa'
urlpatterns = [
    path('search/', external_qa_page, name='external_qa_page'),
    path('ask_question/', ask_question, name='ask_questions'),
    path('edit_question/<int:id>', edit_question, name='edit_question'),
    path('show_answers/<int:id>', show_answers, name='show_answers'),
    path('answer/<int:id>', save_answer, name='save_answer'),
    path('specific_answers/<int:id>', cpecific_answer, name='specific_answers'),
    path('delete/<int:id>', delete, name='delete_question'),
    path('delete-all/', delete_all, name='delete_all_questions')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('golgavzabon/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('plant_leaf_deseases_detector/', include('PLDdetector.urls', namespace='PLDdetector')),
    path('my_plants/', include('my_plants.urls', namespace='my_plants')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('house_plant_species_detector/', include('house_plant_species_detector.urls', namespace='house_plant_species_detector')),
    path('approachs/', include('approachs.urls', namespace='approachs'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/accounts/forms.py
from django import forms
from .models import User, Profile
from django.contrib.auth.forms import ReadOnlyPasswordHashField as ROPHF


# این فرم برای ساخت کاربر جدید در admin panel نمایش داده می شود
class UserCreateForm(forms.ModelForm):
    pass_1 = forms.CharField(widget=forms.PasswordInput)
    pass_2 = forms.CharField(widget=forms.PasswordInput)

    #این فرم از form.ModelForm ارث بری میکند. بعنی برای پر کردن و دریافت فیلدهای یک مدل مشخص ساخته شده است. این مدل در class Meta و فیلد هایش در fields تعریف می شوند.
    class Meta:
        model = User
        fields = ['username', 'email']

    #مساوی بودن و وجود داشتن رمز عبور و تکرار رمز عبور را بررسی می کند.
    def clean_pass_2(self):
        data = self.cleaned_data
        if data["pass_1"] and data["pass_2"] and data["pass_1"] != data["pass_2"]:
            raise forms.ValidationError('passwords dont match')
        return data["pass_2"]

    #حساب کاربری را ذخیره می کند.
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set(self.cleaned_data['pass_2'])
        if commit:
            user.save(using=self._db)

        return user
    
#برای دغییر رمز عبور در admin panel ساخته شده است.
class UserChangeForm(forms.ModelForm):
    password = ROPHF

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_password(self):
        return self.initial['password']


#هنگام ساخت کاربر جدید در سایت این فرم نشان داده میشود.
class UserRegisterForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
                                                                            'style': 'width: 100%; color: black; border: 0.1px solid gray; border-radius: 10px; height: 40px;',
                                                                            }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
                                                           'style': 'width: 100%; color: black; border: 0.1px solid gray; border-radius: 10px; height: 40px;',
                                                           }), initial='')

    def __init__(self, *args, **kwargs):
        email_initial = kwargs.pop('email_initial', None)
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        if email_initial:
            self.fields['email'].initial = email_initial

    password_1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'style': 'width: 100%;  color: black; border: 0.1px solid gray; border-radius: 10px; height: 40px;',
    }))
    password_2 = forms.CharField(widget=forms.PasswordInput(attrs={
                                                                   'style': 'width: 100%; color: black; border: 0.1px solid gray; border-radius: 10px; height: 40px;',
                                                                   }))

#هنگام ورود یک کاربر این فرم نمابش داده می شود.
class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'style': 'width: 300px; background-color: rgb(37,41,44); color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                                                             }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'style': 'width: 300px; background-color: rgb(37,41,44); color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                                                                 }))


#برای به روز رسانی اطلاعات کاربری یک کاربر، این فرم در صفحه پروفایل نمایش داده می شود.
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

        widgets = {
                    'username': forms.TextInput(attrs={
                        'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                    }),
                    'email': forms.TextInput(attrs={
                        'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                    }),

                }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = []


#برای تغییر رمز عبور از این فرم استفاده می شود.
class ChangePassword(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs = {'place_holder' : 'رمز عبور قدیمی',
                                                                       'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                                                                       }))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'place_holder': 'رمز عبور جدید',
                                                              'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;'}
    ))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs = {'place_holder' : 'تکرار رمز عبور جدید',
                                                                          'style': 'width: 300px; background-color: #14191e; color: white; border: 0.1px solid gray; border-radius: 10px; height: 35px;',
                                                                          }))

website/accounts/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import User, Profile
from django.contrib.auth import authenticate, login as dj_login, logout
from django.contrib.auth import update_session_auth_hash
import re



from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
from .models import User


#این فانکش هنگام ساخت کاربر جدید فرم مربوط به ساخت کاربر جدید رو نشان داده و اطلاتعات فرم را بررسی می کند.
def register(request):
    #اگر متد POST باشد یعنی اطلاعاتی از طرف کاربر برای ما ارسال شده و اگر متد GET باشد یعنی کاربر درخواست ننمایش صفحه را دارد.
    error_message = ''
    email_initial = request.GET.get('email', '')

    if request.method == 'POST':
        form = UserRegisterForm(request.POST, email_initial=email_initial)
        if form.is_valid():
            data = form.cleaned_data

            if User.objects.filter(username=data['username']).exists():#چک برای وجود نداشتن نام کاربری از قبل
                error_message = 'نام کاربری قبلا ثبت شده است'
            elif User.objects.filter(email=data['email']).exists():#چک برای وجو نداشتن ایمیل از قبل
                error_message = 'ایمیل قبلا ثبت شده است'
            elif data['password_1'] != data['password_2']:#چک کردن برای مساوی بودن رمز عبور و تکرار رمز عبور
                error_message = 'رمز عبور طابقت ندارد'
            elif len(data['password_1']) <= 8:#چک می کند که طول رمز عبور حتما از 8 بیشتر باشد
                error_message = 'طول رمز عبور شما حداقل باید 10 کاراکتر باشد'
            elif not re.search(r'[A-Z]', data['password_1']):#چک میکند که در رمز عبور حروف بزرگ انگلیسی وجود داشته باشد
                error_message = 'باید در رمز عبور خود از حروف انگلیسی بزرگ استفاده کنید.'
            elif not re.search(r'\d', data['password_1']):#چک می کند که در رمز عبور اعداد وجود داشته باشد
                error_message = 'باید در رمز عبور خود از اعداد استفاده کنید.'
            elif not re.search(r'[!@#$%^&*(),.?":{}|<>]', data['password_1']):#چک میکند که در رمز عبور علامت وجود داشته باشد
                error_message = 'باید در رمز عبور خود از علامت هایی مانند @،#،%، ... استفاده کنید.'
            else:#اگر همه شرط ها درست بودند با استفاده از مدیر مدل User و متد create_user حساب کاربری جدیدی ساخته می شود.
                User.objects.create_user(username=data['username'], email=data['email'], password=data['password_2'])
                messages.success(request, 'حساب کاربری شما ساخته شد', 'success')
                return redirect('home:home')# بازگشت به صفحه خانه
        else:
            error_message = 'آدرس ایمیل شما در قالب درستی نیست'
    else:
        form = UserRegisterForm(email_initial=email_initial)

    context = {'form': form, 'error_message': error_message}
    return render(request, 'accounts/register.html', context)


#هنگام ورود کاربر فرم ورود را نشان می دهد
def login(request):
    error_message = None
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        #در صورت تمیز بودن اطلاعات فرم فرایند ساخت کاربر اجرا می شود.
        if form.is_valid():
            data = form.cleaned_data
           #چک می کند که آیا این نام کاربری از قبل رد دیتا بیس وجود داشته است یا خیر
            if not User.objects.filter(username=data['username']).exists():
                error_message = 'کاربر یافت نشد'

            else:
                user = authenticate(request, username=data['username'], password=data['password'])
                if user is not None:
                    dj_login(request, user)

                    messages.success(request, 'ورود موفقیت آمیر بود', 'success')
                    
                    return redirect('home:home')
                else:
                    error_message = 'نام کاربری یا روز عبور اشتباه است'
                
    else:
        form = UserLoginForm()

    context = {'form': form, 'error_message': error_message}

    return render(request, 'accounts/login.html', context)

#در صفحه پروفایل، فرم به روز رسانی کاربر نمایش داده می شود و در صورت تمیز بودن اطلاعات، اطلاعات کاربری به روز رسانی می شوند.
def profile(request):
    if request.method == 'POST':

        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST,
                                          request.FILES,
                                          instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'پروفایل بروز رسانی شد', 'success')

            return redirect('home:home')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    #پروفایل آن کاربر گرفته می شود
    profile = Profile.objects.get(user_id=request.user.id)
    #گیاهان خانگی موجود در پروفایل کاربر گرفته می شود.
    user_plants = profile.users_plants.all()
    #سوال های پرسیده شده توسط کاربر گرفته می شود.
    user_questions = request.user.questions.all()
    #انتقادات کاربر گرفته می شود.
    user_approachs = request.user.approach.all()
    #تمامی اطلاعات گرفته شده به template فرستاده و ننمایش داده می شود.
    context = {
        'profile' : profile,
        'user_form' : user_form, 
        'profile_form' : profile_form,
        'user_plants' : user_plants,
        'user_questions' : user_questions,
        'user_approachs' : user_approachs
    }

    return render(request, 'accounts/profile.html', context)


#با استفاده از متد logout کاربر خارج می شود.
def signout(request):
    logout(request)
    messages.success(request, 'شما خارج شدید')
    return redirect('home:home')


#در صورت درست بودن رمز عبور قدیمی و مساوی بودن رمز عبور جدید و تکرار ارمز عبور، رمز عبور کاربر تغییر پیدا می کند.
#این ویو مشابه ویو ساخت حساب کاربری عمل می کند.
def change_password(request):
    error = ''
    if request.method == 'POST':
        form = ChangePassword(data=request.POST)

        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            repeat_password = form.cleaned_data['repeat_password']
            if request.user.check_password(old_password):
                if new_password == repeat_password:
                    if len(new_password) <= 8:
                        error = 'رمز عبور شما باید حداقل دارای 8 کاراکتر باشد'
                    elif not re.search(r'[A-Z]', new_password):
                        error = 'باید در رمز عبور شما حروف بزرگ انگلیسی وجود داشته باشد'
                    elif not re.search(r'\d', new_password):
                        error = 'رمز عبور شما باید شامل اعداد باشد'
                    elif not re.search(r'[!@#$%^&*(),.?":{}|<>]', new_password):
                        error = 'رمز عبور شما یاید شامل علامت هایی مثل @،#،... باشد.'
                    else:
                        request.user.set_password(new_password)
                        request.user.save()

                        update_session_auth_hash(request, request.user)

                        messages.success(request, 'رمز عبور شما با موفقیت تغییر کرد')
                        return redirect('accounts:profile')

                else:
                    error = 'رمز عبور جدید با تکرار آن مطابقت ندارد'
            else:
                error = 'رمز عبور قدیمی شما درست نیست'

    else:
        form = ChangePassword()

    context = {
        'form': form,
        'error': error
    }

    return render(request, 'accounts/change_password.html', context)

website/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}پروفایل{% endblock %}

{% block body %}
    <h1 style="color: white">حساب کاربری {{ user.username }}</h1>

    <div class="page-container">
        <div class="right-container">
            <p style="color: white; font-size: 30px">گیاهان شما</p>

                {% if user_plants %}
                    {% for plant in user_plants %}
                        <div class="container" style="display: flex; justify-content: space-between;  align-items: center; border-radius: 20px; border: 1px #595959 solid; padding: 10px; background-color: #262A33FF">
                            <div>
                                 <a href="{% url 'my_plants:plant_detail' plant.id %}" style="color: lightgray; font-size: 20px">
                                    {{ plant.name }} : {{ plant.persian_name }}
                                 </a>

                            </div>

                            <img src="{{ plant.plant_image.url }}" style="height: 70px; border-radius: 10px; border: 1px white solid">

                        </div>
                        <br>
                    {% endfor %}
                    <div style="display: flex; justify-content: center; gap: 10px">
                        <a href="{% url 'my_plants:house_plants_names' %}" class="link-button">اظافه کردن گیاه جدید</a>
                    <a class="big-red-link" href="{% url 'my_plants:user_plant_remover_all' %}">حذف همه گیاهان</a>
                    </div>

                {% else %}
                    <div style="display: flex; justify-content: center">
                        <a href="{% url 'my_plants:house_plants_names' %}" class="link-button">اضافه کردن گیاه جدید</a>
                    </div>
                {% endif %}

            <hr style="color: white">
            <p style="color: white; font-size: 30px">سوالات شما</p>
        {% if user_questions %}
                    <div class="other-fields" style="padding: 10px; display: flex; flex-direction: column;">
            {% for question in user_questions %}
                <div style="display: flex; align-items: center; justify-content: space-between;">
                    <a href="{% url 'qa:edit_question' question.id %}" style="color: lightgray;">{{ question.title }}</a>
                    <div style="display: flex; gap: 10px">
                                    <a class="link" href="{% url 'qa:specific_answers' question.id %}" style="">دیدن پاسخ</a>
                    <a class="red-link" href="{% url 'qa:delete_question' question.id %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-trash3" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                        </svg></a>
                    </div>


                </div>
                <hr style="color: white;">
            {% endfor %}
        </div>

                    <div style="display: flex; gap: 10px; justify-content: center">
                    <a href="{% url 'qa:ask_questions' %}" class="link-button" style="margin-bottom: 20px;">پرسش سوال</a>
                    <a class="big-red-link" href="{% url 'qa:delete_all_questions' %}">حذف همه سوالات</a>
                    </div>
        {% else %}
            <p style="color: lightgray">هنوز سوالی وجود ندارد</p>
            <div style="display: flex; justify-content: center">
                <a href="{% url 'qa:ask_questions' %}" class="link-button" style="margin-bottom: 20px;">پرسش سوال</a>

            </div>

        {% endif %}

        <hr style="color: white">

            <p style="color: white; font-size: 30px">پیشنهادات و انتقادات شما</p>

        {% if user_approachs %}
                    <div class="other-fields" style="padding: 10px; display: flex; flex-direction: column;">
                {% for approach in user_approachs %}
                <div style="display: flex; align-items: center; justify-content: space-between;">
                            <a href="{% url 'approachs:edit_approach' approach.id %}" style="color: lightgray">{{ approach.title }}</a>
                        <div style="display: flex; justify-content: center; gap: 10px">
                            <a class='link' href="{% url 'approachs:approach_answer' approach.id %}">دیدن پاسخ</a>
                            <a class="red-link" href="{% url 'approachs:delete_approach' approach.id %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                            </svg></a>
                        </div>
                     </div>
                    <hr style="color: white">
                {% endfor %}
            </div>
            <div style="display: flex; justify-content: center; gap: 10px">
                <a href="{% url 'approachs:send_approach' %}" class="link-button">ثبت پیشنهاد جدید</a>
                <a href="{% url 'approachs:delete_all_approachs' %}" class="big-red-link">حذف همه پیشنهادات</a>
            </div>
        {% else %}
            <p style="color: lightgray">هنوز پیشنهاد و انتقادی وجود ندارد</p>
            <div style="display: flex; justify-content: center; gap: 10px">
            <a href="{% url 'approachs:send_approach' %}" class="link-button">ثبت پیشنهاد جدید</a>
            </div>
        {% endif%}

        </div>

        <div class="form-container">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">

            <form method="POST" enctype="multipart/form-data" class="profile-update-form">
                {% csrf_token %}
                <p class="field-name">نام کاربری</p>
                {{ user_form.username }}<br>
                <p class="field-name">ایمیل</p>
                {{ user_form.email }}<br>
                {{ profile_form.as_p }}<br><br>

                <button type="submit" class="submit-button">به روز رسانی</button><br><br>

                <div style="display: flex; justify-content: center; gap: 5px">
                <a href="{% url 'accounts:change_password' %}" class="link">تغییر رمز عبور</a><br><br>
                <a href="{% url 'accounts:logout' %}" class="link">خروج از حساب کاربری</a>
                </div>
            </form>
        </div>
    </div>

    <style>
        .page-container {
            display: flex;
            width: 100%;
            flex-direction: row-reverse;
        }

        .right-container {
            flex: 1;
            margin-left: 20px;
        }

        .form-container {
            flex: 0 0 300px;
            display: flex;
            justify-content: center;
            height: 350px;
            margin: 15px;
        }

        .profile-update-form {
            border: 1px #595959 solid;
            border-radius: 20px;
            padding: 20px;
            width: 100%;
            background-color: #262a33;
        }

        .other-fields {
            border: 1px #595959 solid;
            border-radius: 10px;
            margin-bottom: 20px;
            background-color: #262a33;
        }

        .field-name {
            color: white;
        }

        .submit-button {
            background-color: rgba(19, 192, 85, 0.99);
            width: 100%;
            height: 30px;
            border-radius: 10px;
            border: 1px solid #13C055FC;
            color: white;
            margin-bottom: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .submit-button:hover {
            background-color: rgba(97, 206, 139, 0.99);
        }

        .link {
            color: white;
            background-color: #0F7CD5FF;
            border: 1px #0F7CD5FF solid;
            border-radius: 10px;
            width: 140px;
            font-size: 14px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 30px;
            transition: 0.3s;
        }

        .link:hover{
            background-color: #69b3e3;
        }

        .red-link {
            color: white;
            background-color: #c70d0d;
            border: 1px #c70d0d solid;
            border-radius: 10px;
            width: 50px;
            font-size: 14px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 30px;
            transition: 0.3s;
        }

        .red-link:hover {
            background-color: #c96472;
        }

        .big-red-link {
           background-color: #c70d0d;
            color: white;
            border: 1px #c70d0d solid;
            border-radius: 10px;
            height: 30px;
            width: 300px;
            margin-bottom: 20px;
            justify-content: center;
            align-items: center;
            display: flex
        }

        .link-button {
            background-color: rgba(19, 192, 85, 0.99);
            color: white;
            border-radius: 10px;
            border: 1px #13C055FC solid;
            width: 300px;
            height: 30px;
            display: flex;
            margin-left: 10px;
            justify-content: center;
            align-items: center;
        }

        .link-button:hover {
            background-color: rgba(19, 192, 85, 0.99);
        }

        .container {
            display: flex;
            padding-left: 230px;
        }

        @media (max-width: 768px){
            .page-container {
                display: flex;
                flex-direction: column;
                justify-content: center;
                margin-right: 10px;
            }

            .form-container{
                margin:5px;
                width: 90%;
            }

            .other-fields{
                width: 100%;
            }

        }
    </style>
{% endblock %}