website/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


#یو آر ال های مربوط به اپ accounts در اینحا تعریف می شوند.
app_name = "accounts"
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name="login"),
    path('profile/', views.profile, name='profile'), 
    path('logout/', views.signout, name='logout'), 
    path('change_password/', views.change_password, name='change_password'),
] 


if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/approachs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'approachs'
urlpatterns = [
    path('send_approach/', views.send_approach, name='send_approach'),
    path('approach_answer/<int:id>', views.approach_answer, name='approach_answer'),
    path('delete/<int:id>', views.delete, name='delete_approach'),
    path('delete_all/', views.delete_all, name='delete_all_approachs'),
    path('edit_approach/<int:id>', views.edit_approach, name='edit_approach')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/urls.py
from django.urls import path
from .views import home
from django.conf import settings
from django.conf.urls.static import static


app_name = "home"
urlpatterns = [
    path('', home, name="home")
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/my_plants/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#برای نشان دادن توضیحات و پروفایل هر گیاه، حذف و اضافه کردن گیاهان به پروفال کاربر باید id گیاه از طرف لینک ارجاع دهنده دریافت شود.
app_name = 'my_plants'
urlpatterns = [
    path('house plants names/', views.house_plants_names, name='house_plants_names'),
    path('house plants names/<int:id>/', views.plant_detail, name='plant_detail'),
    path('plant_adder/<int:plant_id>/', views.user_plant_adder, name='user_plant_adder'),
    path('plant_remover/<int:plant_id>/', views.user_plant_remover, name='user_plant_remover'),
    path('plant_remover_all/', views.user_plant_remover_all, name='user_plant_remover_all'),
]
if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/qa/urls.py
from django.urls import path
from .views import external_qa_page, ask_question, edit_question, show_answers, save_answer, cpecific_answer, delete, delete_all
from django.conf.urls.static import static
from django.conf import settings

#این اپ دارای صفحه های  :
#پرسش سوال
#ویرایش سوال
#دادن جواب
#حذف سوال
#حذف تمامی سوالات
#صفحه ای که 10 سوال و جوابهای آنها را به صورت تصادفی نمایش می دهد.
app_name = 'qa'
urlpatterns = [
    path('search/', external_qa_page, name='external_qa_page'),
    path('ask_question/', ask_question, name='ask_questions'),
    path('edit_question/<int:id>', edit_question, name='edit_question'),
    path('show_answers/<int:id>', show_answers, name='show_answers'),
    path('answer/<int:id>', save_answer, name='save_answer'),
    path('specific_answers/<int:id>', cpecific_answer, name='specific_answers'),
    path('delete/<int:id>', delete, name='delete_question'),
    path('delete-all/', delete_all, name='delete_all_questions')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('golgavzabon/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('plant_leaf_deseases_detector/', include('PLDdetector.urls', namespace='PLDdetector')),
    path('my_plants/', include('my_plants.urls', namespace='my_plants')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('house_plant_species_detector/', include('house_plant_species_detector.urls', namespace='house_plant_species_detector')),
    path('approachs/', include('approachs.urls', namespace='approachs'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/home.css' %}" rel="stylesheet">

</head>
<body style="background:  #14191e">
    {% include 'messages.html' %}
    {% include 'navbar.html' %}
    {% block body %}{% endblock %}
<footer class="footer-tab" style="margin: 0 auto">
    <footer>
        <div class="footer-container">
            <p style="color: gray">&copy; گیاه شاد</p>
            <nav>
                <ul>
                    <li><a href="{% url 'home:home' %}" style="color: gray">خانه</a></li>
                    <li><a href="{% url 'my_plants:house_plants_names' %}" style="color: gray">فهرست گیاهان خانگی</a></li>
                    <li><a href="{% url 'PLDdetector:plant_diseases_list' %}" style="color: gray">فهرست گیاهان آسیب دیده</a></li>
                </ul>
            </nav>
        </div>
    </footer>
</footer>
<style>
    .footer {
        margin-right: 20px;
        color: gray;
    }
</style>
</body>
</html>

website/templates/messages.html
{% load  static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% if messages %}
    {% for msg in messages %}
        <div class="message-container" style="color: gray; background-color: #494949; border-radius: 10px; border: 1px gray solid; height: 30px; width: 100%; display: flex; justify-content: center; align-items: center">
            <p class="alert alert-{{ tags }}" style="color: lightgray; padding: 10px; margin: 10px 0">{{ msg }}</p>
        </div>
    {% endfor %}

    <style>
        @media (max-width: 768px) {
            .message-container{
                width: 100%;
            }
        }
    </style>
{% endif %}
</body>
</html>

website/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: #14191e">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <img src="{% static 'images/dark_logo.jpg' %}" style="height: 60px">
        </a>
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if not user.is_authenticated %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_plants:house_plants_names' %}">فهرست گیاهان خانگی</a>
                </li>
                {% else %}
            </ul>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'qa:external_qa_page' %}">پرسش و پاسخ</a>
                </li>
            </ul>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'approachs:send_approach' %}">پیشنهادات و انتقادات</a>
                </li>
            </ul>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            گیاهان خانگی
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'house_plant_species_detector:detector' %}" style="justify-content: center; display: flex">تشخیص گیاهان خانگی</a></li>
                            <li><a class="dropdown-item" href="{% url 'my_plants:house_plants_names' %}" style="justify-content: center; display: flex">فهرست گیاهان خانگی</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'house_plant_species_detector:about_model' %}" style="justify-content: center; display: flex">درباره این مدل</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            آسیب شناسی گیاهان
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'PLDdetector:detector_model' %}" style="justify-content: center; display: flex">تشخیص گیاه آسیب دیده</a></li>
                            <li><a class="dropdown-item" href="{% url 'PLDdetector:plant_diseases_list' %}" style="justify-content: center; display: flex">فهرست بیماری گیاهان</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'PLDdetector:about_model' %}" style="justify-content: center; display: flex">درباره این مدل</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                            </svg>
                        </a>
                        {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                            ورود
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z"/>
                                <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z"/>
                            </svg>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</body>
</html>