website/PLDdetector/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


#برای نمیش توضیحات گیاهان، باید ابتدا id آن گیاه از طرف لینک ارجاع دهنده ارسال شود.
app_name = 'PLDdetector'
urlpatterns = [
    path('detector_model/', views.detector_model, name='detector_model'),
    path('plant_diseases_list/', views.plant_diseases_list, name='plant_diseases_list'),
    path('plant_diseased_detail/<int:id>', views.plant_diseased_detail, name='plant_diseased_detail'),
    path('about_model/', views.about_model, name='about_model')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/house_plant_species_detector/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'house_plant_species_detector'

urlpatterns = [
    path('detector/', house_plant_detector, name='detector'),
    path('about_model/', about_model, name='about_model'),
]


if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/my_plants/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#برای نشان دادن توضیحات و پروفایل هر گیاه، حذف و اضافه کردن گیاهان به پروفال کاربر باید id گیاه از طرف لینک ارجاع دهنده دریافت شود.
app_name = 'my_plants'
urlpatterns = [
    path('house plants names/', views.house_plants_names, name='house_plants_names'),
    path('house plants names/<int:id>/', views.plant_detail, name='plant_detail'),
    path('plant_adder/<int:plant_id>/', views.user_plant_adder, name='user_plant_adder'),
    path('plant_remover/<int:plant_id>/', views.user_plant_remover, name='user_plant_remover'),
    path('plant_remover_all/', views.user_plant_remover_all, name='user_plant_remover_all'),
]
if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/qa/urls.py
from django.urls import path
from .views import external_qa_page, ask_question, edit_question, show_answers, save_answer, cpecific_answer, delete, delete_all
from django.conf.urls.static import static
from django.conf import settings

#این اپ دارای صفحه های  :
#پرسش سوال
#ویرایش سوال
#دادن جواب
#حذف سوال
#حذف تمامی سوالات
#صفحه ای که 10 سوال و جوابهای آنها را به صورت تصادفی نمایش می دهد.
app_name = 'qa'
urlpatterns = [
    path('search/', external_qa_page, name='external_qa_page'),
    path('ask_question/', ask_question, name='ask_questions'),
    path('edit_question/<int:id>', edit_question, name='edit_question'),
    path('show_answers/<int:id>', show_answers, name='show_answers'),
    path('answer/<int:id>', save_answer, name='save_answer'),
    path('specific_answers/<int:id>', cpecific_answer, name='specific_answers'),
    path('delete/<int:id>', delete, name='delete_question'),
    path('delete-all/', delete_all, name='delete_all_questions')
]

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('golgavzabon/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('plant_leaf_deseases_detector/', include('PLDdetector.urls', namespace='PLDdetector')),
    path('my_plants/', include('my_plants.urls', namespace='my_plants')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('house_plant_species_detector/', include('house_plant_species_detector.urls', namespace='house_plant_species_detector')),
    path('approachs/', include('approachs.urls', namespace='approachs'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/house_plant_species_detector/models.py
from django.db import models
import torch
import torch.nn as nn
from torch.nn import Conv2d, BatchNorm2d, ReLU, Dropout, AdaptiveAvgPool2d, MaxPool2d
import torchvision.models as torch_models
from efficientnet_pytorch import EfficientNet
from torch.nn import Module

#مدلی است که تصاویری را ذخیره سازی می کند. اما مربوط به کاربر خاصی نمی باشد
class HousePlantImages(models.Model):
    image = models.ImageField(upload_to='house_plant_images')

    def __str__(self):
        return self.image.name

#این کلاس ساختار مدل pytorch را تعریف می کند که برای لود کردن با استفاده از مدل ذخیره شده به صورت dtate_dict ضروری است.
#اطلاعات بیشنر در مورد این مدل را در فایل آموزش مدل تشخیص گونه گیاهان خانگی مشاهده کنید.
class CustomEnsembleModel(Module):
  def __init__(self, num_classes = 47):
    super(CustomEnsembleModel, self).__init__()
    self.resnet50 = torch_models.resnet50(pretrained=True)
    self.efficient_net =   EfficientNet.from_pretrained('efficientnet-b0')

    self.resnet50 = nn.Sequential(*list(self.resnet50.children())[:-2])

    self.custom_resnet = nn.Sequential(
        Conv2d(2048, 1024, kernel_size=3, stride=1, padding=1, bias=False),
        BatchNorm2d(1024),
        ReLU(inplace=True),
        Dropout(p=0.5),
        MaxPool2d(kernel_size=3, stride=2),

        Conv2d(1024, 512, kernel_size=3, stride=1, padding=1, bias=False),
        BatchNorm2d(512),
        ReLU(inplace=True),
        Dropout(p=0.5),
        nn.AdaptiveAvgPool2d((1, 1))
    )

    self.custom_effnet = nn.Sequential(
            Conv2d(1280, 1024, kernel_size=3, stride=1, padding=1, bias=False),
            BatchNorm2d(1024),
            ReLU(inplace=True),
            Dropout(p=0.5),
            MaxPool2d(kernel_size=3, stride=2),

            Conv2d(1024, 512, kernel_size=3, stride=1, padding=1, bias=False),
            BatchNorm2d(512),
            ReLU(inplace=True),
            Dropout(p=0.5),
            AdaptiveAvgPool2d((1, 1))
      )

    self.fc = nn.Linear(512, num_classes)

  def forward(self, x):
     x1 = self.resnet50(x)
     x1 = self.custom_resnet(x1)
     x1 = torch.flatten(x1, 1)
     x1 = self.fc(x1)

     x2 = self.efficient_net.extract_features(x)
     x2 = self.custom_effnet(x2)
     x2 = torch.flatten(x2, 1)
     x2 = self.fc(x2)

     return (x1 + x2) / 2

website/house_plant_species_detector/forms.py
from django import forms
from .models import HousePlantImages

#برای دریافت تصویری از کاربر این فرم را نمایش می دهیم.
class HouseImageForm(forms.ModelForm):
    class Meta:
        model = HousePlantImages
        fields = ['image']
        widgets = {
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control form-control-lg',
                'style': 'background-color: #14191e; color: white; border: 1px solid gray; border-radius: 10px;',
                'placeholder' : 'تصویر خود را وارد کنید'
            }),
        }
        labels = {'image': ''}

website/house_plant_species_detector/views.py
from django.shortcuts import render, get_object_or_404
from .forms import HouseImageForm
from accounts.models import Profile
from .models import CustomEnsembleModel
from torchvision import transforms
import os
import torch
from PIL import Image
from my_plants.models import Plants

class_lookup_dictionary = {
    0: 81, 1: 90, 2: 12,
    3: 46, 4: 91, 5: 20, 6: 58, 7: 8,
    8: 2, 9: 55, 10: 40, 11: 92,
    12: 66, 13: 93, 14: 83, 15: 94,
    16: 69, 17: 73, 18: 95, 19: 30,
    20: 96, 21: 59, 22: 4, 23: 65,
    24: 97, 25: 98, 26: 99, 27: 68,
    28: 19, 29: 100, 30: 60, 31: 72,
    32: 67, 33: 16, 34: 31, 35: 29,
    36: 6, 37: 76, 38: 28, 39: 10,
    40: 101, 41: 89, 42: 56, 43: 34,
    44: 102, 45: 13, 46: 103
}



model = CustomEnsembleModel()
state_dict = torch.load(model_path, map_location=torch.device('cpu'), weights_only=True)
model.load_state_dict(state_dict)

model.eval()


def house_plant_detector(request):
    image_url = None
    plant = None
    plant_id = None
    model_path = os.path.join(os.getcwd(), 'house_plant_species_detector', 'house_plant_species_detector.pth')

    if request.method == 'POST':
        form = HouseImageForm(request.POST, request.FILES)

        model = CustomEnsembleModel()
        state_dict = torch.load(model_path, map_location=torch.device('cpu'), weights_only=True)
        model.load_state_dict(state_dict)

        model.eval()

        if form.is_valid():
            image = form.cleaned_data['image']
            img = Image.open(image).convert('RGB')
            image_url = form.save().image.url

            HEIGHT, WIDTH = 224, 224
            preprocess = transforms.Compose([
                transforms.RandomRotation(30),
                transforms.Resize((HEIGHT, WIDTH)),
                transforms.RandomHorizontalFlip(p=0.5),
                transforms.RandomVerticalFlip(p=0.5),
                transforms.RandomCrop((HEIGHT, WIDTH), padding=4),
                transforms.ToTensor(),
            ])
            print('4')
            img = preprocess(img)
            input_batch = img.unsqueeze(0)
            print('4')
            with torch.no_grad():
                output = model(input_batch)
                _, prediction = torch.max(output, 1)

                plant_id = class_lookup_dictionary[prediction.item()]

                plant = get_object_or_404(Plants, id=plant_id)
                print('5')

    else:
        form = HouseImageForm()

    profile = Profile.objects.get(user_id=request.user.id)
    user_plants = profile.users_plants.all()

    context = {
        'form': form,
        'image_url': image_url,
        'user_plants' : user_plants,
        'plant' : plant,
        'plant_id' : plant_id
    }

    return render(request, 'house_plant_species_detector/detector.html', context)


def about_model(request):
    return render(request, 'house_plant_species_detector/about model.html')

website/house_plant_species_detector/templates/house_plant_species_detector/detector.html
{% extends 'base.html' %}
{% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
{% block title %}
    house plant species detector
{% endblock %}

{% block body %}
    <style>
        body {
            color: white;
        }
        .container-custom {
            border-radius: 35px;
            justify-content: center;
            display: flex;
            padding: 15px;
            border: 1px white solid;

        }
        .submit-btn {
            color: white;
            background-color: #0f7cd5;
            height: 40px;
            width: 300px;
            border: 1px #0f7cd5 solid;
            border-radius: 10px;
            transition: 0.2s;
        }

        .submit-btn:hover {
            background-color: #6ea6d5;
            border: 1px white solid;
        }
        .hr-custom {
            color: white;
        }
        .plant-info {
            color: lightgray;
        }
        .container-bg {
            background-color: #262a33;
            border-radius: 30px;
            border: 1px solid #606060;
            padding: 20px;
            margin: 0px;
            justify-content: center;
        }
        .center-image {
            width: 100%;
            border-radius: 30px;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: auto;
        }

        .plant-card {
            box-shadow: 0 0 70px rgba(103, 255, 114, 0.64),
            0 0 100px rgba(106, 255, 116, 0.71),
            0 0 200px rgba(55, 255, 67, 0.4);

        }

        .form-container {
            box-shadow: 0 0 70px rgba(41, 126, 213, 0.64),
            0 0 100px rgba(98, 29, 180, 0.71),
            0 0 200px rgba(143, 14, 210, 0.4);
        }

        .page-container {
            padding-right: 10px;
            padding-left: 10px;
        }
    </style>

    <div class="page-container">
    <h1>تشخیص گونه گیاهان خانگی</h1><br><br>

        <p style="color: lightgray">
        شما رو به مدل تشخیص نوع گیاهان خانگی معرفی می کنم. از اولین مدل های یادگیری عمیق برای تشخیص نوع گیاهان خانگی فارسی. با وارد کردن یک تصویر از گیاه خانگی خودتون، میتونید گونه اون رو ببینید و اطلاعاتی مثل نام علمی، نام فارسی، شرایط نگهاری و ... رو در مورد اون گیاه مشاهده کنید.
    </p>

    <hr style="color: white">

    <div class="container container-custom">
    <br>
        <div class="form-container" style="display: flex; justify-content: center; width: 100%; border-radius: 30px; background-color: #262a33">
            <form method="post" enctype="multipart/form-data" class="p-3" style="width: 100%;">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.image.label_tag }}
                    {{ form.image }}
                </div>
                <button type="submit" class="submit-btn">ارسال</button>
            </form>
        </div>
    </div><br><br><br>
    {% if plant %}
        <div style="display: flex; justify-content: center">
        <div style="padding: 20px; border: 1px white solid; border-radius: 30px; width: 292px; height: 392px">
        <div class="plant-card" style="display: list-item; justify-content: center; border: 1px solid #606060; border-radius: 20px; width: 250px; height: 350px">
            <img src="{{ plant.plant_image.url }}" style="border-top-right-radius: 20px; border-top-left-radius: 20px; width: 250px">
            <p style="color: white; font-size: 30px; margin-right: 10px">{{ plant.name }}</p>
            <p style="color: white; margin-right: 10px">{{ plant.scientific_name }}</p>
            <p style="color: white; margin-right: 10px">{{ plant.persian_name }}</p>

            <div style="display: flex; justify-content: center; margin: 10px; gap: 10px">

            <a href="{% url 'my_plants:plant_detail' plant.id %}" style="background-color: #22b42e; color: white; border-radius: 10px; border: 1px #22b42e solid; height: 30px; width: 200px; display: flex; justify-content: center; align-items: center ">اطلاعات بیشتر</a>
                            {% if not plant in user_plants %}
                                <a href="{% url 'my_plants:user_plant_adder' plant.id %}" style="background: #2793d0; height: 30px; width: 40px;  border-radius: 10px; display: flex; justify-content: center; align-items: center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-plus" viewBox="0 0 16 16">
                                      <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                                    </svg>
                                </a>
                            {% else %}
                                <a style="background-color: #ef1313; width: 40px; height: 30px; border-radius: 10px; display: flex; justify-content: center; align-items: center" href="{% url 'my_plants:user_plant_remover' plant.id %}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="white" class="bi bi-x" viewBox="0 0 16 16">
                                      <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                                    </svg>
                                </a>
                            {% endif %}
            </div>
        </div>

        </div>
    </div>
    {% else %}
        <p class="plant-info">ابتدا تصویری وارد کنید تا پاسخ رو ببینید</p>
    {% endif %}
    <hr class="hr-custom">
    <div style="display: flex; justify-content: center">
    <div class="container container-bg">
        <p class="plant-info">گیاهان خانگی معمولا اسمای خیلی سختی دارن یا جاهای مختلف به نام های متفاوتی خطاب میشن. همین موضوعات باعث سردرگمی خیلیا میشه که دوست دارن در مورد گیاهان خانگی اطلاعات داشته باشن اما نمیدونن که از کجا اطلاعات درست و کامل رو بدست بیارن. خب! این مدل برای اینجور افراد طراحی شده. این مدل یک مدل یادگیری ماشینه که شما میتونید تصویری از گیاه خونگیتونو بهش بدید و مدل، نام ومشخصات و اطلاعات مفصل و کاملی در مورد اون گیاه رو بهتون بده. این پروژه در بسیاری از برنامه ها مورد استفاده قرار گرفته و خیلی تازگی نداره. اما لازم میدونستم برای یک وبسایتی که درمورد گیاهان خانگی هست این قابلیت رو قرار بدم. امیدوارم که از کارکردن با مدل من لذت ببرید :)</p><br>

        <img src="{% static 'house_plant_detector_image.jpg' %}" class="center-image" >
    </div></div><br><br>
    </div><br>
    <p style="color: gray">توجه داشته باشید که این مدل مانند تمامی مدل های دیگر یادگپیری عمیق، امکان خطا دارد.</p>
{% endblock %}